apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-service
  namespace: loja-veloz
  labels:
    app: pedidos-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: pedidos-service

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: pedidos-service

    spec:
      containers:
        - name: pedidos-service
          image: loja-veloz/pedidos-service:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8082
              protocol: TCP

          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: pedidos-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/loja_veloz"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD

            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"