apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: loja-veloz
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"